# Generated by Django 4.2.4 on 2023-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='navbar_choice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
