# Generated by Django 4.2.4 on 2023-11-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_customuser_navbar_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='navbar_choice',
        ),
    ]
