# Generated by Django 4.2.4 on 2023-11-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/image_preview.jpeg', upload_to='profile_pics/'),
        ),
    ]
