# Generated by Django 4.2.4 on 2023-11-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
