# Generated by Django 4.2.4 on 2023-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteTemplate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetemplate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sitetemplate',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='sitetemplate',
            name='template_file',
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='css_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='html_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='js_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sitetemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SiteSection',
        ),
    ]
