# Generated by Django 4.2.4 on 2023-11-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteTemplate', '0003_usertemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetemplate',
            name='css_content',
        ),
        migrations.RemoveField(
            model_name='sitetemplate',
            name='js_content',
        ),
        migrations.RemoveField(
            model_name='usertemplate',
            name='template_name',
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='siteTemplate.sitetemplate'),
        ),
    ]
