# Generated by Django 4.2.4 on 2023-11-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteTemplate', '0004_remove_sitetemplate_css_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='modified_content',
            field=models.TextField(default=''),
        ),
    ]
