# Generated by Django 4.2.4 on 2023-11-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteTemplate', '0005_alter_usertemplate_modified_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertemplate',
            old_name='modified_content',
            new_name='html_content',
        ),
    ]
